# Generated by Django 3.0 on 2021-09-01 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='categorias.Categoria'),
        ),
        migrations.AddField(
            model_name='partida',
            name='contador',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partida',
            name='max_preguntas',
            field=models.IntegerField(default=5),
        ),
    ]
